name = "collaborative-chess"
compatibility_date = "2024-01-01"
assets = { directory = "./public/" }

main = "src/chess.ts"

[durable_objects]
bindings = [
  { name = "games", class_name = "ChessGame" },
]

[[kv_namespaces]]
binding = "GAMES_TRACKER"
preview_id = "d45d63de0c8a4b3aa3fe59a017c394c4"
id = "3cb8bea4810443ef9495f56b2e0ad4d3"

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ChessGame"]
