name = "collaborative-chess"
compatibility_date = "2024-01-01"
assets = { directory = "./public/" }

main = "src/chess.ts"

[durable_objects]
bindings = [
  { name = "games", class_name = "ChessGame" },
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ChessGame"]
