name = "collaborative-chess"
compatibility_date = "2024-01-01"
assets = { directory = "./public/" }

main = "src/chess.mjs"

[durable_objects]
bindings = [
  { name = "games", class_name = "ChessGame" },
  { name = "limiters", class_name = "RateLimiter" }
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Indicate that you want the ChessGame and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ChessGame", "RateLimiter"]
